{
 "title": "Certsuite Overview",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Quay Pull Events Over Time",
   "type": "barchart",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "rawSql": "SELECT datetime AS time, SUM(count) AS total_count FROM certsuite_usage_db.aggregated_logs WHERE $__timeFilter(datetime) GROUP BY time ORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Quay Pull Events by Month",
   "type": "barchart",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(DATE_FORMAT(datetime, '%Y-%m-01')) AS time, SUM(count) AS total_count FROM certsuite_usage_db.aggregated_logs WHERE $__timeFilter(datetime) GROUP BY time ORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Quay Pull Events by Kind",
   "type": "barchart",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "rawSql": "SELECT DATE(datetime) AS time, kind, SUM(count) AS total_count FROM certsuite_usage_db.aggregated_logs WHERE $__timeFilter(datetime) GROUP BY time, kind ORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "DCI Test Runs Over Time",
   "type": "barchart",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "rawSql": "SELECT DATE(createdAt) AS time, SUM(totalSuccess) AS success, SUM(totalFailures) AS failures, SUM(totalErrors) AS errors, SUM(totalSkips) AS skips FROM dci_components WHERE $__timeFilter(createdAt) GROUP BY time ORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "DCI Test Runs by Month",
   "type": "barchart",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(DATE_FORMAT(createdAt, '%Y-%m-01')) AS time, SUM(totalSuccess) AS total_success, SUM(totalFailures) AS total_failures, SUM(totalErrors) AS total_errors, SUM(totalSkips) AS total_skips FROM dci_components WHERE $__timeFilter(createdAt) GROUP BY time ORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "DCI Test Cases Ranked by Failures",
   "type": "barchart",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "rawSql": "SELECT job_id, commit_hash, SUM(totalFailures) AS totalFailures FROM dci_components WHERE $__timeFilter(createdAt) GROUP BY job_id, commit_hash ORDER BY totalFailures DESC;"
    }
   ]
  }
 ]
}